// This component was generated by @sitecore-search/cli

import { useSearchResultsActions } from '@sitecore-search/react';
import { Select, SortSelect } from '@sitecore-search/ui';

type ResultsPerPageProps = {
  defaultItemsPerPage: number;
};

const ResultsPerPage = ({ defaultItemsPerPage }: ResultsPerPageProps) => {
  const { onResultsPerPageChange } = useSearchResultsActions();
  return (
    <div>
      <label>Results Per Page:</label>
      <Select.Root
        defaultValue={String(defaultItemsPerPage)}
        onValueChange={(v) =>
          onResultsPerPageChange({
            numItems: Number(v),
          })
        }
      >
        <Select.Trigger className="sitecore-select-trigger">
          <Select.SelectValue />
          <Select.Icon />
        </Select.Trigger>
        <Select.Content className="sitecore-select-content">
          <Select.Viewport className="p-1">
            <Select.SelectItem value="24" className="sitecore-select-item">
              <SortSelect.OptionText>24</SortSelect.OptionText>
            </Select.SelectItem>
            <Select.SelectItem value="48" className="sitecore-select-item">
              <SortSelect.OptionText>48</SortSelect.OptionText>
            </Select.SelectItem>
            <Select.SelectItem value="64" className="sitecore-select-item">
              <SortSelect.OptionText>64</SortSelect.OptionText>
            </Select.SelectItem>
          </Select.Viewport>
        </Select.Content>
      </Select.Root>
    </div>
  );
};
export default ResultsPerPage;
