// This component was generated by @sitecore-search/cli

import type { ActionProp, ItemClickedAction } from '@sitecore-search/core';
import { ArticleCard } from '@sitecore-search/ui';
import { ArticleModel } from 'components/Search/SearchResults/SearchResultsWidget';

const DEFAULT_IMG_URL = 'https://placehold.co/500x300?text=No%20Image';

type ArticleCardItemCardProps = {
  article: ArticleModel;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
};

const ArticleHorizontalCard = ({ article, onItemClick, index }: ArticleCardItemCardProps) => {
  return (
    <ArticleCard.Root key={article.id} className="article-horizontal-card">
      <div className="sitecore-article-image-wrapper">
        <ArticleCard.Image
          src={article.image_url || DEFAULT_IMG_URL}
          className="sitecore-article-image"
        />
      </div>
      <ArticleCard.Content className="sitecore-article-content">
        <a
          href="#"
          onClick={(e) => {
            e.preventDefault();
            onItemClick({
              id: article.id,
              index,
              sourceId: article.source_id,
            });
          }}
          className="sitecore-article-link"
        >
          <span aria-hidden="true" className="sitecore-article-span"></span>
          <ArticleCard.Title className="sitecore-article-title">
            {article.title || article.name}
          </ArticleCard.Title>
        </a>
        {article.description && (
          <div className="sitecore-article-content-text">{article.description}</div>
        )}
      </ArticleCard.Content>
    </ArticleCard.Root>
  );
};
export default ArticleHorizontalCard;
